version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pizzashop
    ports:
      - '5432:5432'
    volumes:
      - pizzashop_data:/bitnami/postgresql

volumes:
  pizzashop_data:
